from fastapi import APIRouter
import random

router = APIRouter()

insights_db = [
    {"type": "traffic_warning", "message": "High congestion expected near Wardha Road at 6 PM.", "severity": "high"},
    {"type": "pollution_alert", "message": "Pollution likely to increase in Ward 12 due to heavy traffic density.", "severity": "medium"},
    {"type": "transport_recommendation", "message": "Increase bus frequency on Route 8 to reduce private vehicle density in Sitabuldi.", "severity": "info"},
    {"type": "event_alert", "message": "Weekend market at Itwari resulting in 40% slower traffic movement.", "severity": "medium"}
]

@router.get("/")
def get_city_insights():
    """Returns actionable urban insights generated by the AI engine."""
    # Simulating dynamic insight generation
    selected = random.sample(insights_db, 3)
    return {"status": "success", "insights": selected}
